server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE
  config:
    activate:
      on-profile:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices




