package com.natraj.rating.entiities;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Document("user_rating")
public class Rating {
        @Id//in mongodb  Id's will get auto generated by default, we have nothing to do with id's
        private String ratingId;
        private String userId;
        private String hotelId;
        private int  ratings;
        private String feedback;
    }

